Controllers/GasController.cs
using GWS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace GWS_MVC.Controllers
{
    public class GasController : Controller
    {
        #region lokale Variablen
        private readonly GWS_MVCContext ctx;                                // ETF Context
        private Konfiguration konfigKeyValue = new Konfiguration();         // Konfigurationsdaten
        public GasModel gasModel = new GasModel();                          // GasModel
        public Temperaturen temperaturen = new Temperaturen();              // Temperaturen
        #endregion

        #region Konstruktor GasController
        public GasController(GWS_MVCContext ctx)
        {
            this.ctx = ctx;
        }
        #endregion

        #region Holen der Viewdaten (Loxone Temperaturen)
        public Temperaturen LeseLoxoneTemp()
        {
            temperaturen=Loxone.LeseLoxoneDaten(out string fehlermeldung);  // Auslesen der Daten von Loxone
            ViewBag.Message = fehlermeldung;
            return temperaturen;
        }
        #endregion

        #region ActionResult Index Model mit Daten füllen
        public IActionResult Index()
        {
            DateTime jetzt = DateTime.Now;
            konfigKeyValue = ctx.Konfiguration.Where(id => id.Key== (int)HelperClass.KonfigurationsSchluessel.GasAnbieter).FirstOrDefault();       // auslesen der gespeicherten Anbieter-ID
            bool success = Int32.TryParse(konfigKeyValue.Value,out int number);               // prüfen ob ausgelesener Wert zu parsen ist
           
            gasModel.Id = success == true ? number : 0;                                     // wenn parsen erfolgreich gespeicherten Wert aus der Datenbank übernehmen sonst id=0
            gasModel.KonfigKey= (int)HelperClass.KonfigurationsSchluessel.GasAnbieter;

            gasModel.Ablesedatum = jetzt;
            gasModel.Ableseuhrzeit = jetzt;

            gasModel.AnbieterDaten = ctx.Gas_tarif; // Anbieterdaten aus der Datenbank lesen
            return View(gasModel);
        }
        #endregion

        #region SpeicherDaten in die Datenbank
        [HttpPost]
        public ActionResult SpeicherDaten(GasModel model)
        { 
            Gas_zaehlerstand zaehlerstand = new Gas_zaehlerstand
            {
                ID_Anbieter = model.Id,
                Ablesetag = model.Ablesedatum,
                Zaehlerstand = model.Zaehlerstand,
                Uhrzeit = model.Ableseuhrzeit,
                Temperatur_aussen = model.Aussentemperatur,
                Temperatur_innen = model.Innentemperatur,
                Bemerkungen = model.Bemerkung
            };
          
            int count = ctx.Gas_zaehlerstand.Where(x => x.ID_Anbieter == model.Id && x.Ablesetag == model.Ablesedatum).Count(); // hier wird gefiltert

            if (count == 0)     // der Datensatz ist noch nicht vorhanden
            {
                konfigKeyValue = SpeicherKonfigDaten(Convert.ToString((int)HelperClass.KonfigurationsSchluessel.GasAnbieter), model.Id);        // Auslesen der Konfigurationsdaten und speichern wenn nicht schon gespeichert 1=ausgewählter Gas-Anbieter
                ctx.Gas_zaehlerstand.Add(zaehlerstand);                     // Zufügen des neuen Datensatzes
                ctx.SaveChanges();
                //ViewBag.Message = "Zaehlerstand eingetragen " + model.Ablesedatum.ToShortDateString();
                TempData["Success"] = "Zaehlerstand eingetragen " + model.Ablesedatum.ToShortDateString();      // neu
            }
            else
            {
                //ViewBag.Message = "Datensatz schon vorhanden! "+ model.Ablesedatum.ToShortDateString();
                TempData["Error"] = "Nicht gespeichert, Datensatz schon vorhanden! " + model.Ablesedatum.ToShortDateString();      // neu

                GasModel gasModel = new GasModel();
                gasModel = model;
                gasModel.AnbieterDaten = ctx.Gas_tarif; // Anbieterdaten aus der Datenbank lesen
                
                return View("Index", model);
            }
            gasModel = model;
            gasModel.AnbieterDaten = ctx.Gas_tarif; // Anbieterdaten aus der Datenbank lesen
            //return Redirect("~/Gas"); // auf dem View verbleiben
            return View("Index", model);
        }
        #endregion

        #region Speichern der Konfigurationsdaten
        private Konfiguration SpeicherKonfigDaten(string idConfig, int ausgewaehlterAnbieter)
        {
            bool success = Int32.TryParse(idConfig, out int number);
            if (success)
            {
                konfigKeyValue = ctx.Konfiguration.Where(id => id.Key == number).FirstOrDefault();
            }
            else
            {
                konfigKeyValue.Value = "0";
            }
            if ((konfigKeyValue != null) && (!String.IsNullOrEmpty(konfigKeyValue.Value)))
            {
                if (ausgewaehlterAnbieter != Convert.ToInt32(konfigKeyValue.Value))
                {
                    konfigKeyValue.Value = Convert.ToString(ausgewaehlterAnbieter);
                }
            }
            return konfigKeyValue;
        }
        #endregion
    }
}

Controllers/LulliController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GWS_MVC.Models;

namespace GWS_MVC.Controllers
{
    public class LulliController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public ActionResult SpeicherDaten(LulliModel model)
        {

            return View("Index", model);
        
        }
    }
}

Controllers/StromController.cs
using GWS_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace GWS_MVC.Controllers
{
    public class StromController : Controller
    {
        #region lokale Variablen
        private readonly GWS_MVCContext ctx;                                // ETF Context
        private Konfiguration konfigKeyValue = new Konfiguration();         // Konfigurationsdaten
        public StromModel stromModel = new StromModel();                    // StromModel
        public Temperaturen temperaturen = new Temperaturen();              // Temperaturen
        #endregion

        #region Konstruktor StromController
        public StromController(GWS_MVCContext ctx)
        {
            this.ctx = ctx;
        }
        #endregion

        #region Holen der Viewdaten (Loxone Temperaturen)
        public Temperaturen LeseLoxoneTemp()
        {
            temperaturen = Loxone.LeseLoxoneDaten(out string fehlermeldung);  // Auslesen der Daten von Loxone
            ViewBag.Message = fehlermeldung;
            return temperaturen;
        }
        #endregion

        #region ActionResult Index Model mit Daten füllen
        public IActionResult Index()
        {
            DateTime jetzt = DateTime.Now;
            konfigKeyValue = ctx.Konfiguration.Where(id => id.Key == (int)HelperClass.KonfigurationsSchluessel.StromAnbieter).FirstOrDefault();       // auslesen der gespeicherten Anbieter-ID
            bool success = Int32.TryParse(konfigKeyValue.Value, out int number);               // prüfen ob ausgelesener Wert zu parsen ist

            stromModel.Id = success == true ? number : 0;                                     // wenn parsen erfolgreich gespeicherten Wert aus der Datenbank übernehmen sonst id=0
            stromModel.KonfigKey = (int)HelperClass.KonfigurationsSchluessel.StromAnbieter;

            stromModel.Ablesedatum = jetzt;
            stromModel.Ableseuhrzeit = jetzt;

            stromModel.AnbieterDaten = ctx.Strom_tarif; // Anbieterdaten aus der Datenbank lesen
            return View(stromModel);
        }
        #endregion

        #region SpeicherDaten in die Datenbank
        [HttpPost]
        public ActionResult SpeicherDaten(StromModel model)
        {
            Strom_zaehlerstand zaehlerstand = new Strom_zaehlerstand
            {
                ID_Anbieter = model.Id,
                Ablesetag = model.Ablesedatum,
                Zaehlerstand = model.Zaehlerstand,
                Uhrzeit = model.Ableseuhrzeit,
                Temperatur_aussen = model.Aussentemperatur,
                Temperatur_innen = model.Innentemperatur,
                Bemerkungen = model.Bemerkung
            };
           
            int count = ctx.Strom_zaehlerstand.Where(x => x.ID_Anbieter == model.Id && x.Ablesetag == model.Ablesedatum).Count();   // hier wird gefiltert

            if (count == 0)                         // der Datensatz ist noch nicht vorhanden
            {
                konfigKeyValue = SpeicherKonfigDaten(Convert.ToString((int)HelperClass.KonfigurationsSchluessel.StromAnbieter), model.Id);        // Auslesen der Konfigurationsdaten und speichern wenn nicht schon gespeichert 1=ausgewählter Strom-Anbieter
                ctx.Strom_zaehlerstand.Add(zaehlerstand);                     // Zufügen des neuen Datensatzes
                ctx.SaveChanges();
                //ViewBag.Message = "Zaehlerstand eingetragen " + model.Ablesedatum.ToShortDateString();
                TempData["Success"] = "Zaehlerstand eingetragen " + model.Ablesedatum.ToShortDateString();      // neu
            }
            else
            {
                //ViewBag.Message = "Datensatz schon vorhanden! " + model.Ablesedatum.ToShortDateString();
                TempData["Error"] = "Nicht gespeichert, Datensatz schon vorhanden! " + model.Ablesedatum.ToShortDateString();      // neu

                StromModel stromModel = new StromModel();
                stromModel = model;
                stromModel.AnbieterDaten = ctx.Strom_tarif; // Anbieterdaten aus der Datenbank lesen

                return View("Index", model);
            }
            stromModel = model;
            stromModel.AnbieterDaten = ctx.Strom_tarif; // Anbieterdaten aus der Datenbank lesen
            //return Redirect("~/Strom"); // auf dem View verbleiben
            return View("Index", model);
        }
        #endregion

        #region Speichern der Konfigurationsdaten
        private Konfiguration SpeicherKonfigDaten(string idConfig, int ausgewaehlterAnbieter)
        {
            bool success = Int32.TryParse(idConfig, out int number);
            if (success)
            {
                konfigKeyValue = ctx.Konfiguration.Where(id => id.Key == number).FirstOrDefault();
            }
            else
            {
                konfigKeyValue.Value = "0";
            }
            if ((konfigKeyValue != null) && (!String.IsNullOrEmpty(konfigKeyValue.Value)))
            {
                if (ausgewaehlterAnbieter != Convert.ToInt32(konfigKeyValue.Value))
                {
                    konfigKeyValue.Value = Convert.ToString(ausgewaehlterAnbieter);
                }
            }
            return konfigKeyValue;
        }
        #endregion






    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- <title>@ViewData["Title"] - GWS_MVC</title> -->

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>

    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>

    @*<link rel="stylesheet" href="~/css/site.css" />*@

    <link href="@Url.Content("~/css/site.css")" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/devextreme/css/dx.common.css">
    <link rel="stylesheet" href="~/lib/devextreme/css/dx.light.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    @*<link rel="stylesheet" hhref="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.js"/>*@
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/sweetalert/1.1.3/sweetalert.min.css" />



    @*<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>window.jQuery || document.write(decodeURIComponent('%3Cscript src="js/jquery.min.js"%3E%3C/script%3E'))</script>
        <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.2.3/css/dx.common.css" />
        <link rel="stylesheet" type="text/css" href="https://cdn3.devexpress.com/jslib/21.2.3/css/dx.light.css" />
        <script src="https://cdn3.devexpress.com/jslib/21.2.3/js/dx.all.js"></script>
        <script src="index.js"></script>
        <link rel="stylesheet" type="text/css" href="styles.css" />*@


</head>
<body>
    <div>


    </div>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <!--<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">GWS_MVC</a> -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Gas" asp-action="Index">Gas</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Wasser" asp-action="Index">Wasser</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Strom" asp-action="Index">Strom</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Lulli" asp-action="Index">lulli</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - GWS_MVC <a asp-area="" asp-controller="Home"></a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>

    <script src="~/lib/devextreme/js/dx.all.js"></script>
    <script src="~/lib/devextreme/js/localization/dx.messages.de.js"></script>

    @*<script src="https://cdn3.devexpress.com/jslib/21.1.4/js/dx.all.js"></script>
    <script src="https://cdn3.devexpress.com/jslib/21.1.4/js/localization/dx.messages.de.js"></script>
    <script src="https://unpkg.com/devextreme-cldr-data/de.js"></script>*@

    @*<script src="~/lib/devextreme-aspnet-data/js/dx.aspnet.data.js"></script>*@

    <script>
                    //DevExpress.localization.locale("DE - de");
    </script>

    <script type="text/javascript" src="~/js/toastr.min.js"></script>
    <script src="~/js/sweetalert2/sweetalert.min.js"></script>
    <script src="~/js/sweetalert2/sweetalert2.js"></script>
    <script src="https://cdn.jsdelivr.net/jquery.validation/1.16.0/jquery.validate.min.js"></script>
    <script src="~/js/jquery-validate/jquery.validate.min.js"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>